spring:
  # app specification
  application:
    version: 1.0
    name: Task Management Service with Users

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:task-management-db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  flyway:
    sql-migration-prefix: v
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    repeatable-sql-migration-prefix: R
    locations:
      - classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui