-- v1.0.0 INITIAL CREATE DATABASE
CREATE TABLE USERS (
   ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
   USERNAME VARCHAR(256) NOT NULL UNIQUE,
   EMAIL VARCHAR(256) NOT NULL UNIQUE,
   PASSWORD VARCHAR(256) NOT NULL
);

CREATE TABLE TASKS (
                       ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
                       NAME VARCHAR(100) NOT NULL,
                       DESCRIPTION VARCHAR(256) NOT NULL,
                       STATUS VARCHAR(10) NOT NULL,
                       CREATED_ON TIMESTAMP NOT NULL,
                       DUE_DATE TIMESTAMP NOT NULL,
                       USER_ID BIGINT NULL
);

-- ADD CONSTRAINTS AFTER TABLE CREATIONS
ALTER TABLE TASKS
    ADD CONSTRAINT TASKS_USER_ID_FK
        FOREIGN KEY (USER_ID) REFERENCES USERS;
