-- v1.0.0 INITIAL CREATE DATABASE
CREATE TABLE USERS (
   ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
   USERNAME VARCHAR(256),
   EMAIL VARCHAR(256),
   PASSWORD VARCHAR(256)
);

-- ADD CONSTRAINTS AFTER TABLE CREATIONS
